### ISSUE TITLE
Update dev dependency with security updates

### ISSUE THREAD

**Issue by Blackbaud-IsaacAggrey** [blackbaud/help-client#44]
![Screenshot_2019-05-28 Mail - Isaac Aggrey - Outlook(1)](https://user-images.githubusercontent.com/5076129/58497397-79eddd80-8141-11e9-93d0-3f916e197855.png)

Not all that important since it is just a dev dependency - but it would be a major version update of Webpack. Could be a fun PR to modernize the build tooling but I could see this being closed as a "Won't Fix" , which would still be beneficial to link to explicit decision.

**Comment by Blackbaud-BrandonJones** [comment]
Thanks @Blackbaud-IsaacAggrey!  We managed to update and resolve with https://github.com/blackbaud/help-client/pull/61
